
package br.com.schimidtsolutions.ws.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeuWSService", targetNamespace = "http://ws.schimidtsolutions.com.br/", wsdlLocation = "http://localhost:9080/ws/webservices/meuws?wsdl")
public class MeuWSService
    extends Service
{

    private final static URL MEUWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEUWSSERVICE_EXCEPTION;
    private final static QName MEUWSSERVICE_QNAME = new QName("http://ws.schimidtsolutions.com.br/", "MeuWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/ws/webservices/meuws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEUWSSERVICE_WSDL_LOCATION = url;
        MEUWSSERVICE_EXCEPTION = e;
    }

    public MeuWSService() {
        super(__getWsdlLocation(), MEUWSSERVICE_QNAME);
    }

    public MeuWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEUWSSERVICE_QNAME, features);
    }

    public MeuWSService(URL wsdlLocation) {
        super(wsdlLocation, MEUWSSERVICE_QNAME);
    }

    public MeuWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEUWSSERVICE_QNAME, features);
    }

    public MeuWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeuWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeuWS
     */
    @WebEndpoint(name = "MeuWSPort")
    public MeuWS getMeuWSPort() {
        return super.getPort(new QName("http://ws.schimidtsolutions.com.br/", "MeuWSPort"), MeuWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeuWS
     */
    @WebEndpoint(name = "MeuWSPort")
    public MeuWS getMeuWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.schimidtsolutions.com.br/", "MeuWSPort"), MeuWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEUWSSERVICE_EXCEPTION!= null) {
            throw MEUWSSERVICE_EXCEPTION;
        }
        return MEUWSSERVICE_WSDL_LOCATION;
    }

}
