
package br.com.schimidtsolutions.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeuWS", targetNamespace = "http://ws.schimidtsolutions.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeuWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://ws.schimidtsolutions.com.br/", className = "br.com.schimidtsolutions.ws.client.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://ws.schimidtsolutions.com.br/", className = "br.com.schimidtsolutions.ws.client.GetHelloWorldResponse")
    @Action(input = "http://ws.schimidtsolutions.com.br/MeuWS/getHelloWorldRequest", output = "http://ws.schimidtsolutions.com.br/MeuWS/getHelloWorldResponse")
    public String getHelloWorld();

}
